### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by AC5230** [CommunityDiep/server#6]
On discord, /u/haykam821 is not giving me (my discord: AC#5230) clear enough information. Can someone either give me info via Github or DM me on Discord clear enough information? Thanks.

-Doctor Arena (AC#5230) Closer

**Comment by haykam821** [comment]
Fixed by commit 4a5cf2991c481943a8aeca852f4681f5cd03cfe7. The README now provides instructions that any decent developer should be able to use.

**Comment by AC5230** [comment]
I still don't understand after reading it. I'm not a decent developer.

**Comment by AC5230** [comment]
Never mind.
